package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtdonHang generated by hbm2java
 */
@Entity
@Table(name = "CTDonHang")
public class CtdonHang implements java.io.Serializable {

	private CtdonHangId id;
	private KhachHang khachHang;
	private SanPham sanPham;
	private Integer soLuong;
	private Long donGia;

	public CtdonHang() {
	}

	public CtdonHang(CtdonHangId id, KhachHang khachHang, SanPham sanPham) {
		this.id = id;
		this.khachHang = khachHang;
		this.sanPham = sanPham;
	}

	public CtdonHang(CtdonHangId id, KhachHang khachHang, SanPham sanPham, Integer soLuong, Long donGia) {
		this.id = id;
		this.khachHang = khachHang;
		this.sanPham = sanPham;
		this.soLuong = soLuong;
		this.donGia = donGia;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDh", column = @Column(name = "MaDH", nullable = false) ),
			@AttributeOverride(name = "maSp", column = @Column(name = "MaSP", nullable = false) ) })
	public CtdonHangId getId() {
		return this.id;
	}

	public void setId(CtdonHangId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDH", nullable = false, insertable = false, updatable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSP", nullable = false, insertable = false, updatable = false)
	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	@Column(name = "SoLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "DonGia", precision = 18, scale = 0)
	public Long getDonGia() {
		return this.donGia;
	}

	public void setDonGia(Long donGia) {
		this.donGia = donGia;
	}

}
