package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonHang generated by hbm2java
 */
@Entity
@Table(name = "DonHang")
public class DonHang implements java.io.Serializable {

	private int maDh;
	private KhachHang khachHang;
	private Date ngayDat;
	private Date ngayGiao;
	private Integer tinhTrangThanhToan;
	private Double tongTien;
	private Long phiVanChuyen;
	private Serializable diaChiGiaoHang;
	private Serializable nguoiNhan;
	private Serializable sdt;

	public DonHang() {
	}

	public DonHang(int maDh) {
		this.maDh = maDh;
	}

	public DonHang(int maDh, KhachHang khachHang, Date ngayDat, Date ngayGiao, Integer tinhTrangThanhToan,
			Double tongTien, Long phiVanChuyen, Serializable diaChiGiaoHang, Serializable nguoiNhan, Serializable sdt) {
		this.maDh = maDh;
		this.khachHang = khachHang;
		this.ngayDat = ngayDat;
		this.ngayGiao = ngayGiao;
		this.tinhTrangThanhToan = tinhTrangThanhToan;
		this.tongTien = tongTien;
		this.phiVanChuyen = phiVanChuyen;
		this.diaChiGiaoHang = diaChiGiaoHang;
		this.nguoiNhan = nguoiNhan;
		this.sdt = sdt;
	}

	@Id

	@Column(name = "MaDH", unique = true, nullable = false)
	public int getMaDh() {
		return this.maDh;
	}

	public void setMaDh(int maDh) {
		this.maDh = maDh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH")
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayDat", length = 10)
	public Date getNgayDat() {
		return this.ngayDat;
	}

	public void setNgayDat(Date ngayDat) {
		this.ngayDat = ngayDat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayGiao", length = 10)
	public Date getNgayGiao() {
		return this.ngayGiao;
	}

	public void setNgayGiao(Date ngayGiao) {
		this.ngayGiao = ngayGiao;
	}

	@Column(name = "TinhTrangThanhToan")
	public Integer getTinhTrangThanhToan() {
		return this.tinhTrangThanhToan;
	}

	public void setTinhTrangThanhToan(Integer tinhTrangThanhToan) {
		this.tinhTrangThanhToan = tinhTrangThanhToan;
	}

	@Column(name = "TongTien", precision = 53, scale = 0)
	public Double getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(Double tongTien) {
		this.tongTien = tongTien;
	}

	@Column(name = "PhiVanChuyen", precision = 18, scale = 0)
	public Long getPhiVanChuyen() {
		return this.phiVanChuyen;
	}

	public void setPhiVanChuyen(Long phiVanChuyen) {
		this.phiVanChuyen = phiVanChuyen;
	}

	@Column(name = "DiaChiGiaoHang")
	public Serializable getDiaChiGiaoHang() {
		return this.diaChiGiaoHang;
	}

	public void setDiaChiGiaoHang(Serializable diaChiGiaoHang) {
		this.diaChiGiaoHang = diaChiGiaoHang;
	}

	@Column(name = "NguoiNhan")
	public Serializable getNguoiNhan() {
		return this.nguoiNhan;
	}

	public void setNguoiNhan(Serializable nguoiNhan) {
		this.nguoiNhan = nguoiNhan;
	}

	@Column(name = "SDT")
	public Serializable getSdt() {
		return this.sdt;
	}

	public void setSdt(Serializable sdt) {
		this.sdt = sdt;
	}

}
