package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoaiKh generated by hbm2java
 */
@Entity
@Table(name = "LoaiKH")
public class LoaiKh implements java.io.Serializable {

	private int maCapBac;
	private Serializable tenCapBac;
	private Double chietKhau;
	private Date ngayApDung;
	private Set<KhachHang> khachHangs = new HashSet<KhachHang>(0);

	public LoaiKh() {
	}

	public LoaiKh(int maCapBac) {
		this.maCapBac = maCapBac;
	}

	public LoaiKh(int maCapBac, Serializable tenCapBac, Double chietKhau, Date ngayApDung, Set<KhachHang> khachHangs) {
		this.maCapBac = maCapBac;
		this.tenCapBac = tenCapBac;
		this.chietKhau = chietKhau;
		this.ngayApDung = ngayApDung;
		this.khachHangs = khachHangs;
	}

	@Id

	@Column(name = "MaCapBac", unique = true, nullable = false)
	public int getMaCapBac() {
		return this.maCapBac;
	}

	public void setMaCapBac(int maCapBac) {
		this.maCapBac = maCapBac;
	}

	@Column(name = "TenCapBac")
	public Serializable getTenCapBac() {
		return this.tenCapBac;
	}

	public void setTenCapBac(Serializable tenCapBac) {
		this.tenCapBac = tenCapBac;
	}

	@Column(name = "ChietKhau", precision = 53, scale = 0)
	public Double getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(Double chietKhau) {
		this.chietKhau = chietKhau;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayApDung", length = 10)
	public Date getNgayApDung() {
		return this.ngayApDung;
	}

	public void setNgayApDung(Date ngayApDung) {
		this.ngayApDung = ngayApDung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiKh")
	public Set<KhachHang> getKhachHangs() {
		return this.khachHangs;
	}

	public void setKhachHangs(Set<KhachHang> khachHangs) {
		this.khachHangs = khachHangs;
	}

}
