package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiSanPham generated by hbm2java
 */
@Entity
@Table(name = "LoaiSanPham")
public class LoaiSanPham implements java.io.Serializable {

	private int maLoai;
	private Serializable tenLoaiSp;
	private Set<SanPham> sanPhams = new HashSet<SanPham>(0);

	public LoaiSanPham() {
	}

	public LoaiSanPham(int maLoai) {
		this.maLoai = maLoai;
	}

	public LoaiSanPham(int maLoai, Serializable tenLoaiSp, Set<SanPham> sanPhams) {
		this.maLoai = maLoai;
		this.tenLoaiSp = tenLoaiSp;
		this.sanPhams = sanPhams;
	}

	@Id

	@Column(name = "MaLoai", unique = true, nullable = false)
	public int getMaLoai() {
		return this.maLoai;
	}

	public void setMaLoai(int maLoai) {
		this.maLoai = maLoai;
	}

	@Column(name = "TenLoaiSP")
	public Serializable getTenLoaiSp() {
		return this.tenLoaiSp;
	}

	public void setTenLoaiSp(Serializable tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiSanPham")
	public Set<SanPham> getSanPhams() {
		return this.sanPhams;
	}

	public void setSanPhams(Set<SanPham> sanPhams) {
		this.sanPhams = sanPhams;
	}

}
