package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BaiPost generated by hbm2java
 */
@Entity
@Table(name = "BaiPost", catalog = "QLWEBSITE")
public class BaiPost implements java.io.Serializable {

	private int maPost;
	private TaiKhoan taiKhoan;
	private Serializable noiDung;
	private Date thoiGianPost;
	private Serializable hinhAnh;
	private Set<BinhLuanBaiPost> binhLuanBaiPosts = new HashSet<BinhLuanBaiPost>(0);

	public BaiPost() {
	}

	public BaiPost(int maPost) {
		this.maPost = maPost;
	}

	public BaiPost(int maPost, TaiKhoan taiKhoan, Serializable noiDung, Date thoiGianPost, Serializable hinhAnh,
			Set<BinhLuanBaiPost> binhLuanBaiPosts) {
		this.maPost = maPost;
		this.taiKhoan = taiKhoan;
		this.noiDung = noiDung;
		this.thoiGianPost = thoiGianPost;
		this.hinhAnh = hinhAnh;
		this.binhLuanBaiPosts = binhLuanBaiPosts;
	}

	@Id

	@Column(name = "MaPost", unique = true, nullable = false)
	public int getMaPost() {
		return this.maPost;
	}

	public void setMaPost(int maPost) {
		this.maPost = maPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NguoiPost")
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "NoiDung")
	public Serializable getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(Serializable noiDung) {
		this.noiDung = noiDung;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianPost", length = 23)
	public Date getThoiGianPost() {
		return this.thoiGianPost;
	}

	public void setThoiGianPost(Date thoiGianPost) {
		this.thoiGianPost = thoiGianPost;
	}

	@Column(name = "HinhAnh")
	public Serializable getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(Serializable hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baiPost")
	public Set<BinhLuanBaiPost> getBinhLuanBaiPosts() {
		return this.binhLuanBaiPosts;
	}

	public void setBinhLuanBaiPosts(Set<BinhLuanBaiPost> binhLuanBaiPosts) {
		this.binhLuanBaiPosts = binhLuanBaiPosts;
	}

}
