package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BinhLuanDanhGiaId generated by hbm2java
 */
@Embeddable
public class BinhLuanDanhGiaId implements java.io.Serializable {

	private Date thoiGian;
	private int maKh;
	private int maSp;

	public BinhLuanDanhGiaId() {
	}

	public BinhLuanDanhGiaId(Date thoiGian, int maKh, int maSp) {
		this.thoiGian = thoiGian;
		this.maKh = maKh;
		this.maSp = maSp;
	}

	@Column(name = "ThoiGian", nullable = false, length = 23)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "MaKH", nullable = false)
	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	@Column(name = "MaSP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BinhLuanDanhGiaId))
			return false;
		BinhLuanDanhGiaId castOther = (BinhLuanDanhGiaId) other;

		return ((this.getThoiGian() == castOther.getThoiGian()) || (this.getThoiGian() != null
				&& castOther.getThoiGian() != null && this.getThoiGian().equals(castOther.getThoiGian())))
				&& (this.getMaKh() == castOther.getMaKh()) && (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getThoiGian() == null ? 0 : this.getThoiGian().hashCode());
		result = 37 * result + this.getMaKh();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
