package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BinhLuanBaiPost generated by hbm2java
 */
@Entity
@Table(name = "BinhLuanBaiPost", catalog = "QLWEBSITE")
public class BinhLuanBaiPost implements java.io.Serializable {

	private BinhLuanBaiPostId id;
	private BaiPost baiPost;
	private TaiKhoan taiKhoan;
	private Serializable noiDungBinhLuan;

	public BinhLuanBaiPost() {
	}

	public BinhLuanBaiPost(BinhLuanBaiPostId id, BaiPost baiPost, TaiKhoan taiKhoan) {
		this.id = id;
		this.baiPost = baiPost;
		this.taiKhoan = taiKhoan;
	}

	public BinhLuanBaiPost(BinhLuanBaiPostId id, BaiPost baiPost, TaiKhoan taiKhoan, Serializable noiDungBinhLuan) {
		this.id = id;
		this.baiPost = baiPost;
		this.taiKhoan = taiKhoan;
		this.noiDungBinhLuan = noiDungBinhLuan;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maPost", column = @Column(name = "MaPost", nullable = false) ),
			@AttributeOverride(name = "nguoiBinhLuan", column = @Column(name = "NguoiBinhLuan", nullable = false) ),
			@AttributeOverride(name = "thoiGianBinhLuan", column = @Column(name = "ThoiGianBinhLuan", nullable = false, length = 23) ) })
	public BinhLuanBaiPostId getId() {
		return this.id;
	}

	public void setId(BinhLuanBaiPostId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaPost", nullable = false, insertable = false, updatable = false)
	public BaiPost getBaiPost() {
		return this.baiPost;
	}

	public void setBaiPost(BaiPost baiPost) {
		this.baiPost = baiPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NguoiBinhLuan", nullable = false, insertable = false, updatable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "NoiDungBinhLuan")
	public Serializable getNoiDungBinhLuan() {
		return this.noiDungBinhLuan;
	}

	public void setNoiDungBinhLuan(Serializable noiDungBinhLuan) {
		this.noiDungBinhLuan = noiDungBinhLuan;
	}

}
