package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BinhLuanBaiPostId generated by hbm2java
 */
@Embeddable
public class BinhLuanBaiPostId implements java.io.Serializable {

	private int maPost;
	private int nguoiBinhLuan;
	private Date thoiGianBinhLuan;

	public BinhLuanBaiPostId() {
	}

	public BinhLuanBaiPostId(int maPost, int nguoiBinhLuan, Date thoiGianBinhLuan) {
		this.maPost = maPost;
		this.nguoiBinhLuan = nguoiBinhLuan;
		this.thoiGianBinhLuan = thoiGianBinhLuan;
	}

	@Column(name = "MaPost", nullable = false)
	public int getMaPost() {
		return this.maPost;
	}

	public void setMaPost(int maPost) {
		this.maPost = maPost;
	}

	@Column(name = "NguoiBinhLuan", nullable = false)
	public int getNguoiBinhLuan() {
		return this.nguoiBinhLuan;
	}

	public void setNguoiBinhLuan(int nguoiBinhLuan) {
		this.nguoiBinhLuan = nguoiBinhLuan;
	}

	@Column(name = "ThoiGianBinhLuan", nullable = false, length = 23)
	public Date getThoiGianBinhLuan() {
		return this.thoiGianBinhLuan;
	}

	public void setThoiGianBinhLuan(Date thoiGianBinhLuan) {
		this.thoiGianBinhLuan = thoiGianBinhLuan;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BinhLuanBaiPostId))
			return false;
		BinhLuanBaiPostId castOther = (BinhLuanBaiPostId) other;

		return (this.getMaPost() == castOther.getMaPost()) && (this.getNguoiBinhLuan() == castOther.getNguoiBinhLuan())
				&& ((this.getThoiGianBinhLuan() == castOther.getThoiGianBinhLuan())
						|| (this.getThoiGianBinhLuan() != null && castOther.getThoiGianBinhLuan() != null
								&& this.getThoiGianBinhLuan().equals(castOther.getThoiGianBinhLuan())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaPost();
		result = 37 * result + this.getNguoiBinhLuan();
		result = 37 * result + (getThoiGianBinhLuan() == null ? 0 : this.getThoiGianBinhLuan().hashCode());
		return result;
	}

}
