package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtdonHangId generated by hbm2java
 */
@Embeddable
public class CtdonHangId implements java.io.Serializable {

	private int maDh;
	private int maSp;

	public CtdonHangId() {
	}

	public CtdonHangId(int maDh, int maSp) {
		this.maDh = maDh;
		this.maSp = maSp;
	}

	@Column(name = "MaDH", nullable = false)
	public int getMaDh() {
		return this.maDh;
	}

	public void setMaDh(int maDh) {
		this.maDh = maDh;
	}

	@Column(name = "MaSP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtdonHangId))
			return false;
		CtdonHangId castOther = (CtdonHangId) other;

		return (this.getMaDh() == castOther.getMaDh()) && (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaDh();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
