package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonHang generated by hbm2java
 */
@Entity
@Table(name = "DonHang", catalog = "QLWEBSITE")
public class DonHang implements java.io.Serializable {

	private int maDh;
	private KhachHang khachHang;
	private Date ngayLap;
	private Date ngayGiao;
	private Serializable diaChiGiao;
	private Integer tinhTrangDonHang;
	private Boolean daThanhToan;
	private Long tongTien;
	private Set<CtdonHang> ctdonHangs = new HashSet<CtdonHang>(0);

	public DonHang() {
	}

	public DonHang(int maDh) {
		this.maDh = maDh;
	}

	public DonHang(int maDh, KhachHang khachHang, Date ngayLap, Date ngayGiao, Serializable diaChiGiao,
			Integer tinhTrangDonHang, Boolean daThanhToan, Long tongTien, Set<CtdonHang> ctdonHangs) {
		this.maDh = maDh;
		this.khachHang = khachHang;
		this.ngayLap = ngayLap;
		this.ngayGiao = ngayGiao;
		this.diaChiGiao = diaChiGiao;
		this.tinhTrangDonHang = tinhTrangDonHang;
		this.daThanhToan = daThanhToan;
		this.tongTien = tongTien;
		this.ctdonHangs = ctdonHangs;
	}

	@Id

	@Column(name = "MaDH", unique = true, nullable = false)
	public int getMaDh() {
		return this.maDh;
	}

	public void setMaDh(int maDh) {
		this.maDh = maDh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH")
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayLap", length = 10)
	public Date getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(Date ngayLap) {
		this.ngayLap = ngayLap;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayGiao", length = 10)
	public Date getNgayGiao() {
		return this.ngayGiao;
	}

	public void setNgayGiao(Date ngayGiao) {
		this.ngayGiao = ngayGiao;
	}

	@Column(name = "DiaChiGiao")
	public Serializable getDiaChiGiao() {
		return this.diaChiGiao;
	}

	public void setDiaChiGiao(Serializable diaChiGiao) {
		this.diaChiGiao = diaChiGiao;
	}

	@Column(name = "TinhTrangDonHang")
	public Integer getTinhTrangDonHang() {
		return this.tinhTrangDonHang;
	}

	public void setTinhTrangDonHang(Integer tinhTrangDonHang) {
		this.tinhTrangDonHang = tinhTrangDonHang;
	}

	@Column(name = "DaThanhToan")
	public Boolean getDaThanhToan() {
		return this.daThanhToan;
	}

	public void setDaThanhToan(Boolean daThanhToan) {
		this.daThanhToan = daThanhToan;
	}

	@Column(name = "TongTien", precision = 18, scale = 0)
	public Long getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(Long tongTien) {
		this.tongTien = tongTien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donHang")
	public Set<CtdonHang> getCtdonHangs() {
		return this.ctdonHangs;
	}

	public void setCtdonHangs(Set<CtdonHang> ctdonHangs) {
		this.ctdonHangs = ctdonHangs;
	}

}
