package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "KhachHang", catalog = "QLWEBSITE")
public class KhachHang implements java.io.Serializable {

	private int maKh;
	private LoaiKh loaiKh;
	private Serializable tenKh;
	private Date ngSinh;
	private Serializable gioiTinh;
	private Serializable diaChi;
	private Serializable sdt;
	private Integer diemTichLuy;
	private Set<DonHang> donHangs = new HashSet<DonHang>(0);
	private Set<BinhLuanDanhGia> binhLuanDanhGias = new HashSet<BinhLuanDanhGia>(0);

	public KhachHang() {
	}

	public KhachHang(int maKh) {
		this.maKh = maKh;
	}

	public KhachHang(int maKh, LoaiKh loaiKh, Serializable tenKh, Date ngSinh, Serializable gioiTinh,
			Serializable diaChi, Serializable sdt, Integer diemTichLuy, Set<DonHang> donHangs,
			Set<BinhLuanDanhGia> binhLuanDanhGias) {
		this.maKh = maKh;
		this.loaiKh = loaiKh;
		this.tenKh = tenKh;
		this.ngSinh = ngSinh;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
		this.diemTichLuy = diemTichLuy;
		this.donHangs = donHangs;
		this.binhLuanDanhGias = binhLuanDanhGias;
	}

	@Id

	@Column(name = "MaKH", unique = true, nullable = false)
	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LoaiKH")
	public LoaiKh getLoaiKh() {
		return this.loaiKh;
	}

	public void setLoaiKh(LoaiKh loaiKh) {
		this.loaiKh = loaiKh;
	}

	@Column(name = "TenKH")
	public Serializable getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(Serializable tenKh) {
		this.tenKh = tenKh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgSinh", length = 10)
	public Date getNgSinh() {
		return this.ngSinh;
	}

	public void setNgSinh(Date ngSinh) {
		this.ngSinh = ngSinh;
	}

	@Column(name = "GioiTinh")
	public Serializable getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Serializable gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT")
	public Serializable getSdt() {
		return this.sdt;
	}

	public void setSdt(Serializable sdt) {
		this.sdt = sdt;
	}

	@Column(name = "DiemTichLuy")
	public Integer getDiemTichLuy() {
		return this.diemTichLuy;
	}

	public void setDiemTichLuy(Integer diemTichLuy) {
		this.diemTichLuy = diemTichLuy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<DonHang> getDonHangs() {
		return this.donHangs;
	}

	public void setDonHangs(Set<DonHang> donHangs) {
		this.donHangs = donHangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachHang")
	public Set<BinhLuanDanhGia> getBinhLuanDanhGias() {
		return this.binhLuanDanhGias;
	}

	public void setBinhLuanDanhGias(Set<BinhLuanDanhGia> binhLuanDanhGias) {
		this.binhLuanDanhGias = binhLuanDanhGias;
	}

}
