package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SanPhamKhuyenMaiId generated by hbm2java
 */
@Embeddable
public class SanPhamKhuyenMaiId implements java.io.Serializable {

	private int maKm;
	private int maSp;

	public SanPhamKhuyenMaiId() {
	}

	public SanPhamKhuyenMaiId(int maKm, int maSp) {
		this.maKm = maKm;
		this.maSp = maSp;
	}

	@Column(name = "MaKM", nullable = false)
	public int getMaKm() {
		return this.maKm;
	}

	public void setMaKm(int maKm) {
		this.maKm = maKm;
	}

	@Column(name = "MaSP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SanPhamKhuyenMaiId))
			return false;
		SanPhamKhuyenMaiId castOther = (SanPhamKhuyenMaiId) other;

		return (this.getMaKm() == castOther.getMaKm()) && (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaKm();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
