package entities;
// Generated Dec 20, 2015 1:45:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SanPhamKhuyenMai generated by hbm2java
 */
@Entity
@Table(name = "SanPhamKhuyenMai", catalog = "QLWEBSITE")
public class SanPhamKhuyenMai implements java.io.Serializable {

	private SanPhamKhuyenMaiId id;
	private CtkhuyenMai ctkhuyenMai;
	private SanPham sanPham;
	private Integer chietKhau;

	public SanPhamKhuyenMai() {
	}

	public SanPhamKhuyenMai(SanPhamKhuyenMaiId id, CtkhuyenMai ctkhuyenMai, SanPham sanPham) {
		this.id = id;
		this.ctkhuyenMai = ctkhuyenMai;
		this.sanPham = sanPham;
	}

	public SanPhamKhuyenMai(SanPhamKhuyenMaiId id, CtkhuyenMai ctkhuyenMai, SanPham sanPham, Integer chietKhau) {
		this.id = id;
		this.ctkhuyenMai = ctkhuyenMai;
		this.sanPham = sanPham;
		this.chietKhau = chietKhau;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maKm", column = @Column(name = "MaKM", nullable = false) ),
			@AttributeOverride(name = "maSp", column = @Column(name = "MaSP", nullable = false) ) })
	public SanPhamKhuyenMaiId getId() {
		return this.id;
	}

	public void setId(SanPhamKhuyenMaiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKM", nullable = false, insertable = false, updatable = false)
	public CtkhuyenMai getCtkhuyenMai() {
		return this.ctkhuyenMai;
	}

	public void setCtkhuyenMai(CtkhuyenMai ctkhuyenMai) {
		this.ctkhuyenMai = ctkhuyenMai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSP", nullable = false, insertable = false, updatable = false)
	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	@Column(name = "ChietKhau")
	public Integer getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(Integer chietKhau) {
		this.chietKhau = chietKhau;
	}

}
