package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BinhLuanDanhGia generated by hbm2java
 */
@Entity
@Table(name = "BinhLuan_DanhGia")
public class BinhLuanDanhGia implements java.io.Serializable {

	private BinhLuanDanhGiaId id;
	private KhachHang khachHang;
	private SanPham sanPham;
	private Integer danhGia;
	private String noiDung;

	public BinhLuanDanhGia() {
	}

	public BinhLuanDanhGia(BinhLuanDanhGiaId id, KhachHang khachHang, SanPham sanPham) {
		this.id = id;
		this.khachHang = khachHang;
		this.sanPham = sanPham;
	}

	public BinhLuanDanhGia(BinhLuanDanhGiaId id, KhachHang khachHang, SanPham sanPham, Integer danhGia,
			String noiDung) {
		this.id = id;
		this.khachHang = khachHang;
		this.sanPham = sanPham;
		this.danhGia = danhGia;
		this.noiDung = noiDung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maBgdg", column = @Column(name = "MaBGDG", nullable = false) ),
			@AttributeOverride(name = "maKh", column = @Column(name = "MaKH", nullable = false) ),
			@AttributeOverride(name = "maSp", column = @Column(name = "MaSP", nullable = false) ) })
	public BinhLuanDanhGiaId getId() {
		return this.id;
	}

	public void setId(BinhLuanDanhGiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaKH", nullable = false, insertable = false, updatable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSP", nullable = false, insertable = false, updatable = false)
	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	@Column(name = "DanhGia")
	public Integer getDanhGia() {
		return this.danhGia;
	}

	public void setDanhGia(Integer danhGia) {
		this.danhGia = danhGia;
	}

	@Column(name = "NoiDung")
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
