package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BinhLuanDanhGiaId generated by hbm2java
 */
@Embeddable
public class BinhLuanDanhGiaId implements java.io.Serializable {

	private int maBgdg;
	private int maKh;
	private int maSp;

	public BinhLuanDanhGiaId() {
	}

	public BinhLuanDanhGiaId(int maBgdg, int maKh, int maSp) {
		this.maBgdg = maBgdg;
		this.maKh = maKh;
		this.maSp = maSp;
	}

	@Column(name = "MaBGDG", nullable = false)
	public int getMaBgdg() {
		return this.maBgdg;
	}

	public void setMaBgdg(int maBgdg) {
		this.maBgdg = maBgdg;
	}

	@Column(name = "MaKH", nullable = false)
	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	@Column(name = "MaSP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BinhLuanDanhGiaId))
			return false;
		BinhLuanDanhGiaId castOther = (BinhLuanDanhGiaId) other;

		return (this.getMaBgdg() == castOther.getMaBgdg()) && (this.getMaKh() == castOther.getMaKh())
				&& (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaBgdg();
		result = 37 * result + this.getMaKh();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
