package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CtkhuyenMai generated by hbm2java
 */
@Entity
@Table(name = "CTKhuyenMai")
public class CtkhuyenMai implements java.io.Serializable {

	private CtkhuyenMaiId id;
	private SanPham sanPham;
	private Double chietKhau;
	private Date ngayBd;
	private Date ngayKt;

	public CtkhuyenMai() {
	}

	public CtkhuyenMai(CtkhuyenMaiId id, SanPham sanPham) {
		this.id = id;
		this.sanPham = sanPham;
	}

	public CtkhuyenMai(CtkhuyenMaiId id, SanPham sanPham, Double chietKhau, Date ngayBd, Date ngayKt) {
		this.id = id;
		this.sanPham = sanPham;
		this.chietKhau = chietKhau;
		this.ngayBd = ngayBd;
		this.ngayKt = ngayKt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maKm", column = @Column(name = "MaKM", nullable = false) ),
			@AttributeOverride(name = "maSp", column = @Column(name = "MaSP", nullable = false) ) })
	public CtkhuyenMaiId getId() {
		return this.id;
	}

	public void setId(CtkhuyenMaiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaSP", nullable = false, insertable = false, updatable = false)
	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	@Column(name = "ChietKhau", precision = 53, scale = 0)
	public Double getChietKhau() {
		return this.chietKhau;
	}

	public void setChietKhau(Double chietKhau) {
		this.chietKhau = chietKhau;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayBD", length = 10)
	public Date getNgayBd() {
		return this.ngayBd;
	}

	public void setNgayBd(Date ngayBd) {
		this.ngayBd = ngayBd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayKT", length = 10)
	public Date getNgayKt() {
		return this.ngayKt;
	}

	public void setNgayKt(Date ngayKt) {
		this.ngayKt = ngayKt;
	}

}
