package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiNv generated by hbm2java
 */
@Entity
@Table(name = "LoaiNV")
public class LoaiNv implements java.io.Serializable {

	private int maLoai;
	private Long luongCoBan;
	private Double phuCap;
	private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

	public LoaiNv() {
	}

	public LoaiNv(int maLoai) {
		this.maLoai = maLoai;
	}

	public LoaiNv(int maLoai, Long luongCoBan, Double phuCap, Set<NhanVien> nhanViens) {
		this.maLoai = maLoai;
		this.luongCoBan = luongCoBan;
		this.phuCap = phuCap;
		this.nhanViens = nhanViens;
	}

	@Id

	@Column(name = "MaLoai", unique = true, nullable = false)
	public int getMaLoai() {
		return this.maLoai;
	}

	public void setMaLoai(int maLoai) {
		this.maLoai = maLoai;
	}

	@Column(name = "LuongCoBan", precision = 18, scale = 0)
	public Long getLuongCoBan() {
		return this.luongCoBan;
	}

	public void setLuongCoBan(Long luongCoBan) {
		this.luongCoBan = luongCoBan;
	}

	@Column(name = "PhuCap", precision = 53, scale = 0)
	public Double getPhuCap() {
		return this.phuCap;
	}

	public void setPhuCap(Double phuCap) {
		this.phuCap = phuCap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiNv")
	public Set<NhanVien> getNhanViens() {
		return this.nhanViens;
	}

	public void setNhanViens(Set<NhanVien> nhanViens) {
		this.nhanViens = nhanViens;
	}

}
