package entities;
// Generated Dec 9, 2015 9:41:21 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "NhanVien")
public class NhanVien implements java.io.Serializable {

	private int maNv;
	private LoaiNv loaiNv;
	private Serializable tenNv;
	private Date ngSinh;
	private Serializable gioiTinh;
	private Serializable diaChi;
	private Serializable sdt;

	public NhanVien() {
	}

	public NhanVien(int maNv) {
		this.maNv = maNv;
	}

	public NhanVien(int maNv, LoaiNv loaiNv, Serializable tenNv, Date ngSinh, Serializable gioiTinh,
			Serializable diaChi, Serializable sdt) {
		this.maNv = maNv;
		this.loaiNv = loaiNv;
		this.tenNv = tenNv;
		this.ngSinh = ngSinh;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.sdt = sdt;
	}

	@Id

	@Column(name = "MaNV", unique = true, nullable = false)
	public int getMaNv() {
		return this.maNv;
	}

	public void setMaNv(int maNv) {
		this.maNv = maNv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LoaiNV")
	public LoaiNv getLoaiNv() {
		return this.loaiNv;
	}

	public void setLoaiNv(LoaiNv loaiNv) {
		this.loaiNv = loaiNv;
	}

	@Column(name = "TenNV")
	public Serializable getTenNv() {
		return this.tenNv;
	}

	public void setTenNv(Serializable tenNv) {
		this.tenNv = tenNv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgSinh", length = 10)
	public Date getNgSinh() {
		return this.ngSinh;
	}

	public void setNgSinh(Date ngSinh) {
		this.ngSinh = ngSinh;
	}

	@Column(name = "GioiTinh")
	public Serializable getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Serializable gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SDT")
	public Serializable getSdt() {
		return this.sdt;
	}

	public void setSdt(Serializable sdt) {
		this.sdt = sdt;
	}

}
