//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiPost()
        {
            this.BinhLuanBaiPosts = new HashSet<BinhLuanBaiPost>();
        }
    
        public int MaPost { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianPost { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> NguoiPost { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string TieuDe { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanBaiPost> BinhLuanBaiPosts { get; set; }
    }
}
