//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuanBaiPost
    {
        public int MaPost { get; set; }
        public int NguoiBinhLuan { get; set; }
        public System.DateTime ThoiGianBinhLuan { get; set; }
        public string NoiDungBinhLuan { get; set; }
    
        public virtual BaiPost BaiPost { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
