//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuan_DanhGia = new HashSet<BinhLuan_DanhGia>();
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTKhuyenMais = new HashSet<CTKhuyenMai>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> DanhMuc { get; set; }
        public Nullable<int> SLTon { get; set; }
        public string NhaSanXuat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan_DanhGia> BinhLuan_DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTKhuyenMai> CTKhuyenMais { get; set; }
        public virtual DanhMuc DanhMuc1 { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
